Bootstrap: docker

From: continuumio/miniconda3

%files
    environment.yml

%post
    /gpfs/home/snagaraja/miniconda3/condabin/conda env create -f environment.yml

%runscript
    exec /gpfs/home/snagaraja/miniconda3/envs/$(head -n 1 environment.yml | cut -f 2 -d ' ')/bin/"$@"